import { prisma } from '../../database/runtime-client.js';
import { ApiError } from '../../lib/api-error.js';
import { normalizeEmail } from '../auth/auth.validation.js';

const include={skills:{include:{skill:{select:{id:true,name:true,normalizedName:true}}}},education:{orderBy:{startDate:'desc'}},experience:{orderBy:{startDate:'desc'}},resumes:{select:{id:true,originalFileName:true,mimeType:true,fileSize:true,processingStatus:true,uploadedAt:true,processedAt:true,isPrimary:true}},applications:{select:{id:true,applicationCode:true,currentStatus:true,job:{select:{id:true,jobCode:true,title:true}}}}};
const audit=(actor,action,id,metadata)=>({actorUserId:actor.id,action,entityType:'CANDIDATE',entityId:id,metadata,ipAddress:actor.ipAddress,userAgent:actor.userAgent});
const serializeCandidate=value=>({...value,resumes:value.resumes.map(resume=>({...resume,fileSize:resume.fileSize.toString()}))});
async function replaceChildren(tx,id,{skills,education,experience}) { if(skills!==undefined){await tx.candidateSkill.deleteMany({where:{candidateId:id}});for(const s of skills){const normalizedName=s.name.trim().toLowerCase();await tx.skill.createMany({data:[{name:s.name.trim(),normalizedName}],skipDuplicates:true});const skill=await tx.skill.findUniqueOrThrow({where:{normalizedName}});await tx.candidateSkill.create({data:{candidateId:id,skillId:skill.id,yearsOfExperience:s.yearsOfExperience,proficiency:s.proficiency,source:s.source}});}} if(education!==undefined){await tx.candidateEducation.deleteMany({where:{candidateId:id}});if(education.length)await tx.candidateEducation.createMany({data:education.map(x=>({...x,candidateId:id}))});} if(experience!==undefined){await tx.candidateExperience.deleteMany({where:{candidateId:id}});if(experience.length)await tx.candidateExperience.createMany({data:experience.map(x=>({...x,candidateId:id}))});} }
async function find(id){const value=await prisma.candidate.findFirst({where:{id,deletedAt:null},include});if(!value)throw new ApiError(404,'CANDIDATE_NOT_FOUND','The requested candidate was not found.');return serializeCandidate(value);}
export async function createCandidate(input,actor){const {skills=[],education=[],experience=[],...data}=input;const normalizedEmail=normalizeEmail(data.email);const duplicateCount=await prisma.candidate.count({where:{normalizedEmail,deletedAt:null}});const candidate=await prisma.$transaction(async tx=>{const row=await tx.candidate.create({data:{...data,email:normalizedEmail,normalizedEmail}});await replaceChildren(tx,row.id,{skills,education,experience});await tx.auditLog.create({data:audit(actor,'CANDIDATE_CREATED',row.id,{duplicateEmailDetected:duplicateCount>0,skillCount:skills.length,educationCount:education.length,experienceCount:experience.length})});return tx.candidate.findUniqueOrThrow({where:{id:row.id},include});});return{candidate:serializeCandidate(candidate),warning:duplicateCount>0?{code:'DUPLICATE_CANDIDATE_EMAIL',message:'Another candidate with this email already exists.'}:null};}
export async function listCandidates({page,limit,search,skill,location,minimumExperienceYears,maximumExperienceYears}){const where={deletedAt:null,...(location?{location:{equals:location,mode:'insensitive'}}:{}),...(minimumExperienceYears!=null||maximumExperienceYears!=null?{totalExperienceYears:{...(minimumExperienceYears!=null?{gte:minimumExperienceYears}:{}),...(maximumExperienceYears!=null?{lte:maximumExperienceYears}:{})}}:{}),...(skill?{skills:{some:{skill:{normalizedName:skill.toLowerCase()}}}}:{}),...(search?{OR:['firstName','lastName','email','currentJobTitle','currentCompany'].map(field=>({[field]:{contains:search,mode:'insensitive'}}))}:{})};const[candidates,total]=await prisma.$transaction([prisma.candidate.findMany({where,include,orderBy:[{createdAt:'desc'},{id:'asc'}],skip:(page-1)*limit,take:limit}),prisma.candidate.count({where})]);return{candidates:candidates.map(serializeCandidate),meta:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
export const getCandidate=find;
export async function updateCandidate(id,input,actor){await find(id);const{skills,education,experience,...data}=input;if(data.email!==undefined){data.email=normalizeEmail(data.email);data.normalizedEmail=data.email;}const candidate=await prisma.$transaction(async tx=>{await tx.candidate.update({where:{id},data});await replaceChildren(tx,id,{skills,education,experience});await tx.auditLog.create({data:audit(actor,'CANDIDATE_UPDATED',id,{changedFields:Object.keys(input)})});return tx.candidate.findUniqueOrThrow({where:{id},include});});return serializeCandidate(candidate);}
