import {randomUUID}from'node:crypto';import argon2 from'argon2';import{UserRole}from'@prisma/client';import request from'supertest';import{afterAll,beforeAll,describe,expect,it}from'vitest';import{app}from'../../src/app.js';import{prisma}from'../../src/database/runtime-client.js';import{signAccessToken}from'../../src/modules/auth/auth.jwt.js';
const run=randomUUID();let tokens={},candidate;const base={firstName:'Casey',lastName:`Candidate-${run}`,email:`CASEY-${run}@Example.Local`,phone:'555-0100',location:'Chicago',professionalSummary:'Experienced developer.',totalExperienceYears:4,currentJobTitle:'Engineer',currentCompany:'Example',linkedinUrl:'https://linkedin.com/in/example',portfolioUrl:'https://example.com',skills:[{name:' React ',yearsOfExperience:3,source:'MANUAL'}],education:[{institution:'Example University',degree:'BS',startDate:'2015-01-01',endDate:'2019-01-01'}],experience:[{company:'Example Co',jobTitle:'Engineer',startDate:'2020-01-01',isCurrent:true}]};
beforeAll(async()=>{const hash=await argon2.hash('CandidateTest!123');for(const role of Object.values(UserRole)){const u=await prisma.user.create({data:{firstName:'Can',lastName:role,email:`can-${role}-${run}@test.local`,passwordHash:hash,role}});tokens[role]=signAccessToken(u);}});afterAll(()=>prisma.$disconnect());const auth=role=>({Authorization:`Bearer ${tokens[role]}`});const create=(role=UserRole.RECRUITER,data=base)=>request(app).post('/api/v1/candidates').set(auth(role)).send(data);
describe.sequential('Candidate Management API',()=>{
it('CAN-01 recruiter creates candidate',async()=>{const r=await create();expect(r.status).toBe(201);candidate=r.body.data;});
it('CAN-02 admin creates candidate',async()=>expect((await create(UserRole.ADMINISTRATOR,{...base,email:`admin-${run}@test.local`})).status).toBe(201));
it('CAN-03 unauthorized role rejected',async()=>expect((await create(UserRole.INTERVIEWER)).status).toBe(403));
it('CAN-04 unauthenticated rejected',async()=>expect((await request(app).post('/api/v1/candidates').send(base)).status).toBe(401));
it('CAN-05 validation works',async()=>expect((await create(UserRole.RECRUITER,{})).status).toBe(400));
it('CAN-06 email normalization',async()=>expect(candidate.email).toBe(base.email.trim().toLowerCase()));
it('CAN-07 duplicate email detected',async()=>{const r=await create(UserRole.RECRUITER,{...base,firstName:'Duplicate'});expect(r.status).toBe(201);expect(r.body.meta.warnings[0].code).toBe('DUPLICATE_CANDIDATE_EMAIL');});
it('CAN-08 candidate skills created',async()=>expect(candidate.skills).toHaveLength(1));
it('CAN-09 skill normalization',async()=>expect(candidate.skills[0].skill.normalizedName).toBe('react'));
it('CAN-10 education created',async()=>expect(candidate.education).toHaveLength(1));
it('CAN-11 work experience created',async()=>expect(candidate.experience).toHaveLength(1));
it('CAN-12 negative experience rejected',async()=>expect((await create(UserRole.RECRUITER,{...base,email:`negative-${run}@x.test`,totalExperienceYears:-1})).status).toBe(400));
it('CAN-13 candidate list pagination',async()=>{const r=await request(app).get('/api/v1/candidates?limit=1').set(auth(UserRole.RECRUITER));expect(r.body.data).toHaveLength(1);expect(r.body.meta.limit).toBe(1);});
it('CAN-14 search by name',async()=>expect((await request(app).get(`/api/v1/candidates?search=${run}`).set(auth(UserRole.RECRUITER))).body.data.length).toBeGreaterThan(0));
it('CAN-15 search by email',async()=>expect((await request(app).get(`/api/v1/candidates?search=casey-${run}`).set(auth(UserRole.RECRUITER))).body.data.length).toBeGreaterThan(0));
it('CAN-16 skill filtering',async()=>expect((await request(app).get('/api/v1/candidates?skill=REACT').set(auth(UserRole.RECRUITER))).body.data.length).toBeGreaterThan(0));
it('CAN-17 location filtering',async()=>expect((await request(app).get('/api/v1/candidates?location=chicago').set(auth(UserRole.RECRUITER))).body.data.length).toBeGreaterThan(0));
it('CAN-18 retrieve candidate',async()=>{const r=await request(app).get(`/api/v1/candidates/${candidate.id}`).set(auth(UserRole.RECRUITER));expect(r.status).toBe(200);expect(r.body.data.id).toBe(candidate.id);});
it('CAN-19 missing candidate 404',async()=>expect((await request(app).get(`/api/v1/candidates/${randomUUID()}`).set(auth(UserRole.RECRUITER))).body.error.code).toBe('CANDIDATE_NOT_FOUND'));
it('CAN-20 update candidate',async()=>{const r=await request(app).patch(`/api/v1/candidates/${candidate.id}`).set(auth(UserRole.RECRUITER)).send({currentJobTitle:'Senior Engineer'});expect(r.body.data.currentJobTitle).toBe('Senior Engineer');});
it('CAN-21 protected fields rejected',async()=>expect((await request(app).patch(`/api/v1/candidates/${candidate.id}`).set(auth(UserRole.RECRUITER)).send({id:randomUUID()})).status).toBe(400));
it('CAN-22 child relationships remain consistent',async()=>{const r=await request(app).patch(`/api/v1/candidates/${candidate.id}`).set(auth(UserRole.RECRUITER)).send({skills:[{name:'Node.js',source:'MANUAL'}],education:[],experience:[]});expect(r.body.data.skills).toHaveLength(1);expect(r.body.data.skills[0].skill.normalizedName).toBe('node.js');expect(r.body.data.education).toHaveLength(0);expect(r.body.data.experience).toHaveLength(0);});
it('CAN-23 audit created',async()=>{const actions=(await prisma.auditLog.findMany({where:{entityType:'CANDIDATE',entityId:candidate.id}})).map(x=>x.action);expect(actions).toEqual(expect.arrayContaining(['CANDIDATE_CREATED','CANDIDATE_UPDATED']));});
it('CAN-24 password/security fields never appear',async()=>{const r=await request(app).get(`/api/v1/candidates/${candidate.id}`).set(auth(UserRole.RECRUITER));expect(r.text).not.toMatch(/passwordHash|accessToken|storageKey|extractedText/);});
});
