import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { environment } from './config/environment.js';
import { errorHandler, notFoundHandler } from './middleware/error-handler.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { applicationRouter } from './modules/applications/application.routes.js';
import { candidateRouter } from './modules/candidates/candidate.routes.js';
import { jobRouter } from './modules/jobs/job.routes.js';
import { userRouter } from './modules/users/user.routes.js';
import { resumeRouter } from './modules/resumes/resume.routes.js';
import { screeningRouter } from './modules/screening/screening.routes.js';
import { healthRouter } from './routes/health.js';

export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: environment.WEB_ORIGIN, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use('/api/v1/health', healthRouter);
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/applications', applicationRouter);
app.use('/api/v1/candidates', candidateRouter);
app.use('/api/v1/jobs', jobRouter);
app.use('/api/v1/resumes', resumeRouter);
app.use('/api/v1/screenings', screeningRouter);
app.use('/api/v1/users', userRouter);
app.use(notFoundHandler);
app.use(errorHandler);
