import{Prisma,UserRole}from'@prisma/client';import{prisma}from'../../database/runtime-client.js';import{ApiError}from'../../lib/api-error.js';
const summaryInclude={candidate:{select:{id:true,firstName:true,lastName:true,email:true}},job:{select:{id:true,jobCode:true,title:true,status:true}},assignedRecruiter:{select:{id:true,firstName:true,lastName:true,email:true,role:true}}};const detailInclude={...summaryInclude,statusHistory:{include:{changedBy:{select:{id:true,firstName:true,lastName:true}}},orderBy:{createdAt:'asc'}},notes:{where:{deletedAt:null},include:{author:{select:{id:true,firstName:true,lastName:true}}},orderBy:{createdAt:'asc'}}};
const audit=(actor,action,id,metadata)=>({actorUserId:actor.id,action,entityType:'APPLICATION',entityId:id,metadata,ipAddress:actor.ipAddress,userAgent:actor.userAgent});
const notFound=entity=>new ApiError(404,`${entity}_NOT_FOUND`,`The requested ${entity.toLowerCase()} was not found.`);const duplicate=()=>new ApiError(409,'APPLICATION_ALREADY_EXISTS','This candidate already has an application for the selected job.');
async function validateRecruiter(id){if(id==null)return;const user=await prisma.user.findFirst({where:{id,isActive:true},select:{role:true}});if(!user)throw notFound('RECRUITER');if(![UserRole.ADMINISTRATOR,UserRole.RECRUITER].includes(user.role))throw new ApiError(400,'INVALID_RECRUITER_ASSIGNMENT','The assigned user must be an active recruiter or administrator.');}
async function find(id){const app=await prisma.application.findUnique({where:{id},include:detailInclude});if(!app)throw notFound('APPLICATION');return app;}
export async function createApplication(input,actor){const{notes,...data}=input;const[candidate,job]=await Promise.all([prisma.candidate.findFirst({where:{id:data.candidateId,deletedAt:null},select:{id:true}}),prisma.job.findUnique({where:{id:data.jobId},select:{id:true,status:true}})]);if(!candidate)throw notFound('CANDIDATE');if(!job)throw notFound('JOB');if(job.status!=='OPEN')throw new ApiError(409,'JOB_NOT_OPEN','New applications can only be created for open jobs.');await validateRecruiter(data.assignedRecruiterId);try{return await prisma.$transaction(async tx=>{const app=await tx.application.create({data:{...data,currentStatus:'APPLIED'}});await tx.applicationStatusHistory.create({data:{applicationId:app.id,previousStatus:null,newStatus:'APPLIED',changedById:actor.id,reason:'Application created.'}});if(notes)await tx.applicationNote.create({data:{applicationId:app.id,authorId:actor.id,content:notes}});await tx.auditLog.create({data:audit(actor,'APPLICATION_CREATED',app.id,{candidateId:data.candidateId,jobId:data.jobId,assignedRecruiterId:data.assignedRecruiterId??null})});return tx.application.findUniqueOrThrow({where:{id:app.id},include:detailInclude});});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')throw duplicate();throw e;}}
export async function listApplications({page,limit,status,jobId,candidateId,assignedRecruiterId,dateFrom,dateTo,search}){const where={...(status?{currentStatus:status}:{}),...(jobId?{jobId}:{}),...(candidateId?{candidateId}:{}),...(assignedRecruiterId?{assignedRecruiterId}:{}),...(dateFrom||dateTo?{appliedAt:{...(dateFrom?{gte:dateFrom}:{}),...(dateTo?{lte:dateTo}:{})}}:{}),...(search?{OR:[{applicationCode:{contains:search,mode:'insensitive'}},{candidate:{OR:[{firstName:{contains:search,mode:'insensitive'}},{lastName:{contains:search,mode:'insensitive'}},{email:{contains:search,mode:'insensitive'}}]}},{job:{OR:[{jobCode:{contains:search,mode:'insensitive'}},{title:{contains:search,mode:'insensitive'}}]}}]}:{})};const[applications,total]=await prisma.$transaction([prisma.application.findMany({where,include:summaryInclude,orderBy:[{appliedAt:'desc'},{id:'asc'}],skip:(page-1)*limit,take:limit}),prisma.application.count({where})]);return{applications,meta:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
export const getApplication=find;
export async function updateApplication(id,input,actor){const current=await find(id);await validateRecruiter(input.assignedRecruiterId);const updated=await prisma.$transaction(async tx=>{const row=await tx.application.update({where:{id},data:input});await tx.auditLog.create({data:audit(actor,'APPLICATION_UPDATED',id,{changedFields:Object.keys(input)})});if(input.assignedRecruiterId!==undefined&&input.assignedRecruiterId!==current.assignedRecruiterId)await tx.auditLog.create({data:audit(actor,'APPLICATION_RECRUITER_ASSIGNED',id,{previousRecruiterId:current.assignedRecruiterId,newRecruiterId:input.assignedRecruiterId})});return tx.application.findUniqueOrThrow({where:{id:row.id},include:detailInclude});});return updated;}
export async function updateApplicationStatus(id,{status,reason},actor){const current=await find(id);if(current.currentStatus===status)return current;return prisma.$transaction(async tx=>{const timestamps={...(status==='WITHDRAWN'?{withdrawnAt:new Date()}:{}),...(status==='REJECTED'?{rejectedAt:new Date()}:{}),...(status==='HIRED'?{hiredAt:new Date()}:{})};const row=await tx.application.update({where:{id},data:{currentStatus:status,lastStatusChangedAt:new Date(),...timestamps}});await tx.applicationStatusHistory.create({data:{applicationId:id,previousStatus:current.currentStatus,newStatus:status,changedById:actor.id,reason}});await tx.auditLog.create({data:audit(actor,'APPLICATION_STATUS_CHANGED',id,{previousStatus:current.currentStatus,newStatus:status,reasonProvided:Boolean(reason)})});return tx.application.findUniqueOrThrow({where:{id:row.id},include:detailInclude});});}
export async function addApplicationNote(id,{content},actor){await find(id);return prisma.$transaction(async tx=>{const note=await tx.applicationNote.create({data:{applicationId:id,authorId:actor.id,content},include:{author:{select:{id:true,firstName:true,lastName:true}}}});await tx.auditLog.create({data:audit(actor,'APPLICATION_NOTE_ADDED',id,{noteId:note.id})});return note;});}
